// 2.19.0 UI tests of the ride-alongs (owner requests from #655), own container (start.sh, isolated test database).
// - the profile picture presets are herons (the app icon's line drawing on a dark disc, one prop each; no sloth left),
//   generated by tools/make_avatars.py (byte-identical)
// - the magnifier stays visible on a phone while the sidebar drawer is open: a round search button next to the drawer
//   (44 px, on screen, not under the drawer); one tap closes the drawer and opens search; none without a drawer
// - "+" next to 👍 👎 ❤️ in the agent chat and the team chat: the emoji grid, any emoji, one more stop for ← →
// jsdom + Firefox touch at 360 / 390 / 412 and the Fold 904, a mouse at 1440. Screenshots with P2190R_SHOTS=<dir>.
const {execFileSync} = require('child_process');
const fs = require('fs');
const path = require('path');
const {boot, sleep, B, login} = require('./boot');
const F = []; let ok = 0;
const check = (c, what) => { if (c) ok++; else { F.push(what); console.log('FAIL:', what); } };
const firefox = require('./ff')({tag: 'p2190_ride_ui', check, shots: 'P2190R_SHOTS'});
const H = {'Content-Type': 'application/json', 'X-Requested-With': 'kalmido'};
const DATA = process.argv[2] || path.join(__dirname, '.data');
const ROOT = path.join(__dirname, '..');
execFileSync('bash', [path.join(__dirname, 'start.sh'), DATA], {stdio: 'ignore'});
let CK;
const call = async (method, url, body, ck = CK) => { const r = await fetch(B + url.replace(/^\//, ''), {method, headers: {...H, Cookie: ck}, body: body ? JSON.stringify(body) : undefined}); return {...(await r.json().catch(() => ({}))), status: r.status}; };
const tcall = async (method, url, tok, body) => { const r = await fetch(B + 'api/v1' + url, {method, headers: {'Content-Type': 'application/json', Authorization: 'Bearer ' + tok}, body: body ? JSON.stringify(body) : undefined}); return {status: r.status, ...(await r.json().catch(() => ({})))}; };
const until = async (fn, n = 40) => { for (let i = 0; i < n; i++) { const x = await fn(); if (x) return x; await sleep(150); } return fn(); };
const click = (w, el) => el.dispatchEvent(new w.MouseEvent('click', {bubbles: true, cancelable: true}));
const key = (w, el, k) => el.dispatchEvent(new w.KeyboardEvent('keydown', {key: k, bubbles: true, cancelable: true}));

(async () => {
  // ================= the heron profile pictures (files, no container needed)
  const presets = ['coffee', 'headphones', 'camera', 'sleepy', 'laptop', 'plant', 'robot', 'shades', 'party', 'glasses'];
  for (const p of presets) {
    const svg = fs.readFileSync(path.join(ROOT, 'static', 'avatars', p + '.svg'), 'utf8');
    check(svg.includes('M54 48C51 39 49 32 51 25C53 20 58 19 61 22') && svg.includes('M61 22L77 26') && /aria-label="[^"]+"/.test(svg) && svg.length < 2000,
      `avatar ${p}: the heron of the app icon, labelled, small`);
    check(!/sloth|faultier/i.test(svg), `avatar ${p}: no sloth`);
  }
  const gen = path.join(ROOT, 'tools', 'make_avatars.py');
  if (fs.existsSync(gen)) {
    let r = ''; try { r = execFileSync(process.env.PYTHON || 'python3', [gen, '--check'], {encoding: 'utf8'}); } catch (e) { r = String(e.stdout || e.message); }
    check(/checked 10/.test(r), 'tools/make_avatars.py --check: the files are what it draws ' + r.trim());
  } else check(false, 'tools/make_avatars.py exists');

  await sleep(600);
  await fetch(B + 'api/auth/setup', {method: 'POST', headers: H, body: JSON.stringify({username: 'alice', display_name: 'Alice', password: 'password123'})});
  CK = await login('alice');
  await call('POST', '/api/admin/setup', {lang: 'en', collab_all: true, time_all: true, modules: ['cal', 'comments', 'agents']});
  await call('PATCH', '/api/settings', {features: 'cal,collab,comments,agents', lang: 'en', tour: 'done'});
  const ME = (await call('GET', '/api/state')).me.id;
  const BOB = (await call('POST', '/api/users', {username: 'bob', display_name: 'Bob', password: 'password123'})).id;
  const CB = await login('bob');
  await call('PATCH', '/api/settings', {features: 'cal,collab,comments,agents', tour: 'done'}, CB);
  const ag = await call('POST', '/api/admin/agents', {scopes: ['write'], username: 'claude', display_name: 'Claude'});
  const AG = ag.id, TOK = ag.token;
  const L = (await call('POST', '/api/lists', {name: 'Home'})).id;
  await call('PUT', `/api/lists/${L}/members`, {user_id: BOB, role: 'edit'});
  await call('PUT', `/api/lists/${L}/members`, {user_id: AG, role: 'edit'});
  await call('POST', '/api/tasks', {title: 'Water the plants', list_id: L});
  await tcall('GET', '/agent/events?since=0', TOK);
  const q1 = await tcall('POST', `/agent/chats/${ME}`, TOK, {body: 'All green.'});

  // ================= jsdom: the avatar picker offers the herons
  let w = await boot({user: 'alice', hash: 'today'}), d = w.document;
  w.eval(`settingsModal('account')`); await sleep(400);
  const av = [...d.querySelectorAll('.smodal #a-avpick [data-av] img')].map(i => i.getAttribute('src'));
  check(presets.every(p => av.includes(`/static/avatars/${p}.svg`)), 'the picture picker offers the ten herons ' + av.length);
  [...d.querySelectorAll('.modal')].forEach(m => m.remove());

  // ================= jsdom: "+" in the agent chat
  w.eval(`chatOpen(${AG})`); await until(() => d.querySelectorAll('#chat-msgs .cmsg').length >= 1, 60);
  const msg = () => d.querySelector(`#chat-msgs .cmsg[data-mid="${q1.id}"]`);
  const plus = () => msg()?.querySelector('.rxrow [data-act="rx-more"]');
  check(plus() && plus().getAttribute('aria-haspopup') === 'dialog' && plus().getAttribute('aria-label') === 'More reactions' && plus().tabIndex === -1, 'agent chat: "+" More reactions after 👍 👎 ❤️ (not an extra Tab stop)');
  const up = msg().querySelector('.rxrow [data-e="up"]'); up.focus(); key(w, up, 'End');
  check(d.activeElement === plus(), '← → / End reach the "+"');
  click(w, plus()); await sleep(200);
  const grid = [...d.querySelectorAll('#pop .rxgrid button')];
  check(grid.length >= 10 && d.querySelector('#pop #rx-in'), 'the emoji grid opens (with "any emoji")');
  click(w, grid.find(b => b.dataset.rx === '\u{1F389}'));
  check(await until(async () => (await call('GET', `/api/agents/${AG}/chat`)).messages.find(m => m.id === q1.id)?.reactions.some(r => r.emoji === '\u{1F389}')), 'picked 🎉: stored on the message');
  check(await until(() => msg()?.querySelector('.rxrow .rx.on[data-e="\u{1F389}"]')), '… and shown as my reaction chip');
  w.eval('chatClose()'); w.close();

  // ================= jsdom: "+" in the team chat
  w = await boot({user: 'alice', hash: 'today'}); d = w.document;
  w.eval(`go('team')`); await until(() => d.querySelector('.tclist .tcrow'));
  click(w, d.querySelector('.tclist .tcrow')); await until(() => d.querySelector('#tc-in'));
  const RID = w.eval('S.tc.rid');
  const m1 = await call('POST', `/api/team/rooms/${RID}/messages`, {body: 'Dinner at 7?'}, CB);
  w.eval('teamChanged()');
  const tm = () => d.querySelector(`#tc-msgs .cmsg[data-mid="${m1.id}"]`);
  await until(() => tm());
  click(w, tm().querySelector('.rxrow [data-act="rx-more"]')); await sleep(200);
  d.querySelector('#pop #rx-in').value = '🍝';
  click(w, d.querySelector('#pop [data-rx-ok]'));
  check(await until(async () => (await call('GET', `/api/team/rooms/${RID}/messages`)).messages.find(m => m.id === m1.id)?.reactions?.some(r => r.emoji === '🍝')), 'team chat: any emoji via "+"');
  w.close();

  // ================= Firefox: the magnifier next to the open drawer, real taps
  const ffLogin = async ({ev, nav}, theme) => {
    await nav(B + 'static/icon.svg');
    await ev(`(() => { localStorage.clear(); localStorage.setItem('tasks.theme', '"${theme}"'); return 1; })()`);
    return ev(`fetch('/api/auth/login', {method: 'POST', headers: {'Content-Type': 'application/json', 'X-Requested-With': 'kalmido'}, body: JSON.stringify({username: 'alice', password: 'password123'})}).then(r => r.status)`);
  };
  const ready = async ev => { for (let i = 0; i < 40 && !(await ev(`!!document.querySelector('#top h1')`).catch(() => false)); i++) await sleep(250); await sleep(800); };
  const tapper = ({cmd, ctx}) => async (x, y) => {
    await cmd('input.performActions', {context: ctx, actions: [{type: 'pointer', id: 't1', parameters: {pointerType: 'touch'}, actions: [{type: 'pointerMove', x: Math.round(x), y: Math.round(y)}, {type: 'pointerDown', button: 0}, {type: 'pause', duration: 60}, {type: 'pointerUp', button: 0}]}]});
    await cmd('input.releaseActions', {context: ctx});
  };
  const SS = `(() => { const b = document.querySelector('#scrim .sidesearch'); if (!b) return null; const r = b.getBoundingClientRect(), s = document.querySelector('#side').getBoundingClientRect(), cs = getComputedStyle(b);
    const top = document.elementFromPoint(r.left + r.width / 2, r.top + r.height / 2);
    return {vis: cs.display !== 'none' && r.width > 0, w: Math.round(r.width), h: Math.round(r.height), l: Math.round(r.left), r: Math.round(r.right), t: Math.round(r.top), sideR: Math.round(s.right), onTop: b === top || b.contains(top), iw: innerWidth, lab: b.getAttribute('aria-label')}; })()`;
  for (const [vw, vh, th] of [[360, 780, 'light'], [390, 844, 'dark'], [412, 915, 'light']]) await firefox(async o => {
    const {cmd, ev, ctx, shot} = o, tap = tapper(o), tag = `${vw}x${vh} ${th}`;
    await cmd('browsingContext.setViewport', {context: ctx, viewport: {width: vw, height: vh}});
    check(await ffLogin(o, th) === 200, tag + ': login');
    await o.nav(B + '#l/' + L); await ready(ev);
    check(await ev(`(() => { const b = document.querySelector('#scrim .sidesearch'); return !b || getComputedStyle(b).display === 'none' || document.querySelector('#scrim').classList.contains('hidden'); })()`), `${tag}: drawer closed: no extra search button`);
    const mb = await ev(`(() => { const r = document.querySelector('#top [data-act="side"]').getBoundingClientRect(); return {x: r.left + r.width / 2, y: r.top + r.height / 2}; })()`);
    await tap(mb.x, mb.y);
    check(await until(() => ev(`!!document.querySelector('#side.open')`), 30), `${tag}: one tap opens the drawer`);
    await sleep(400);
    const s = await ev(SS);
    check(s && s.vis && s.w >= 43.5 && s.h >= 43.5 && s.l >= s.sideR && s.r <= s.iw && s.onTop && s.lab === 'Search and commands',
      `${tag}: the magnifier next to the open drawer: 44 px, on screen, not under the drawer, tappable ` + JSON.stringify(s));
    await shot(`p2190r-${vw}x${vh}-${th}-drawer.png`);
    await tap(s.l + s.w / 2, s.t + s.h / 2);
    check(await until(() => ev(`!!document.querySelector('.palette') && !document.querySelector('#side.open')`), 30), `${tag}: one tap: the drawer closes, search opens`);
    await ev(`(() => { closePalette(); return 1; })()`);
    // the chat "+" with a real tap
    await o.nav(B + '#agents/' + AG); await ready(ev); await sleep(800);
    await ev(`(() => { document.querySelector('#chat-msgs .cmsg[data-mid="${q1.id}"] .rxrow .rxtog')?.click(); return 1; })()`); await sleep(300);  // 2.23.0 (#823): behind the smiley
    const pb = await ev(`(() => { const e = document.querySelector('#chat-msgs .cmsg[data-mid="${q1.id}"] .rxrow [data-act="rx-more"]'); e.scrollIntoView({block: 'center'}); const r = e.getBoundingClientRect(); return {x: r.left + r.width / 2, y: r.top + r.height / 2, w: r.width, h: r.height}; })()`);
    check(pb.w >= 43.5 && pb.h >= 43.5, `${tag}: "+" is a 44 px target ` + JSON.stringify(pb));
    await tap(pb.x, pb.y);
    check(await until(() => ev(`!!document.querySelector('#pop:not(.hidden) .rxgrid')`), 30), `${tag}: one tap opens the emoji grid`);
    check(await ev(`document.documentElement.scrollWidth - innerWidth`) <= 0, `${tag}: nothing sideways`);
    await shot(`p2190r-${vw}x${vh}-${th}-rxmore.png`);
    await ev(`(() => { closePop(); return 1; })()`);
  }, true);
  await firefox(async o => {
    const {cmd, ev, ctx} = o;
    await cmd('browsingContext.setViewport', {context: ctx, viewport: {width: 1440, height: 900}});
    check(await ffLogin(o, 'light') === 200, '1440: login');
    await o.nav(B + '#l/' + L); await ready(ev);
    check(await ev(`(() => { const b = document.querySelector('#scrim .sidesearch'); return !b || getComputedStyle(b).display === 'none'; })()`), '1440: no drawer, no extra search button');
  }, false);

  console.log(`${ok} ok, ${F.length} failed`);
  process.exit(F.length ? 1 : 0);
})().catch(e => { console.error(e); process.exit(1); });
