"""Kalmido server package. app.py is the entry point; docs/ARCHITECTURE.md explains the layout.

The modules are loaded in the fixed ORDER below (it is the order the code had in the former single app.py): routes, request
hooks and error handlers register in that order, and each module may use names of EARLIER modules at import time
(`from ..core.db import connect` at the top). A name of a LATER module is imported inside the function that needs it
(at call time, when every module is loaded) -- that keeps the import graph free of cycles.
"""
import importlib

ORDER = (
    "core.config",
    "core.schema",
    "core.i18n",
    "core.db",
    "accounts.session",
    "accounts.pictures",
    "accounts.login",
    "accounts.oidc",
    "core.access",
    "core.serializers",
    "core.pages",
    "core.instance",
    "core.state",
    "lists.lists",
    "lists.groups",
    "lists.ownership",
    "lists.sections",
    "tasks.validation",
    "tasks.tasks",
    "tasks.roadmap",
    "tasks.lifecycle",
    "tasks.attachments",
    "integrations.paperless",
    "tasks.batch",
    "collab.comments",
    "collab.news",
    "personal.habits",
    "personal.timetrack",
    "accounts.settings",
    "accounts.onboarding",
    "accounts.users",
    "lists.templates",
    "tasks.dependencies",
    "lists.projects",
    "lists.fields",
    "personal.stats",
    "calendars.icalfeed",
    "calendars.caldav",
    "integrations.importers",
    "notify.push",
    "notify.alerts",
    "calendars.subscriptions",
    "admin.backup",
    "api.v1",
    "tasks.dayplan",
    "api.openapi",
    "integrations.webhooks",
    "agents.core",
    "collab.reactions",
    "agents.chat",
    "agents.admin",
    "agents.api",
    "agents.proposals",
    "agents.usage",
    "lists.public",
    "integrations.git",
    "integrations.errorreports",
    "api.projects",
    "api.scopes",
    "collab.notes",
    "collab.teamchat",
    "integrations.mail",
    "family.family",
    "family.web",
    "family.carddav",
    "family.v1",
    "events.model",
    "events.ics",
    "events.web",
    "events.dav",
    "events.v1",
    "contacts.model",
    "contacts.carddav",
    "contacts.web",
    "contacts.v1",
    "startup",
)
MODULES = [importlib.import_module(f"{__name__}.{m}") for m in ORDER]
