/* Kalmido browser demo: the texts of the demo itself (banner, notices, the simulated agent) and the sample data, in the six
   app languages. The app's own texts come from static/i18n as usual. Loaded before shim.js (see tools/build_demo.py). */
'use strict';
window.KDEMO_TEXTS = {
  en: {
    banner: 'Demo – your data stays in this browser', reset: 'Reset demo', install: 'Install Kalmido',
    resetAsk: 'Reset the demo? Everything you changed here is deleted and the sample data comes back.',
    gated: 'Not available in the demo – install Kalmido (5 minutes)', gatedMore: 'This needs a server: push notifications, calendar sync, agents, Git, webhooks, sign-in providers and working with other people run on your own Kalmido.',
    installLink: 'Install in 5 minutes', close: 'Close', simulated: 'simulated',
    agentName: 'Demo-Agent', agentTexts: ['simulated: checking the contact form', 'simulated: writing the test report', 'simulated: waiting for your approval'],
    agentDone: 'simulated: staging site published', agentChatHello: 'Hi! I am a simulated agent. In a real Kalmido an AI assistant or a bot works on shared lists through the API, and you approve what matters.',
    agentChatOk: 'Thanks – (simulated) the staging site is online. I will post the test report as a comment.', agentChatNo: 'Understood – (simulated) I will not publish it and wait for your feedback.',
    agentChatReply: 'This is the demo: I only answer with prepared lines. Install Kalmido to connect a real agent.',
    jobTitle: 'Publish the staging site for the client review?', jobLog: 'Checked the build and the links. Waiting for your approval.',
    project: 'Website relaunch for Café Aurora', secs: ['Discovery', 'Design', 'Development', 'Launch'],
    personal: 'Personal', budget: 'Budget', effort: 'Effort', small: 'Small', medium: 'Medium', large: 'Large',
    status: 'Design is approved, development is on schedule', ms1: 'Design approved', ms2: 'Go-live',
    t: {
      kickoff: 'Kickoff workshop with the client', sitemap: 'Draft the sitemap and the content plan', moodboard: 'Moodboard and colour palette',
      layouts: 'Layouts for the home page and menu', layoutsNote: '**Goal:** a warm, calm site that sells the breakfast menu.\n\n- [x] Mobile first\n- [ ] Desktop variant\n- [ ] Accessibility check (contrast, font size)',
      subA: 'Home page', subB: 'Menu page', subC: 'Contact and opening hours',
      approval: 'Get the design approved by the client', comment: 'The client likes the warm colours and wants bigger photos of the cakes.',
      cms: 'Set up the CMS and the staging site', form: 'Contact form sends no confirmation e-mail', booking: 'Table booking on the home page',
      images: 'Optimise the photos (WebP, lazy loading)', menuBug: 'Menu prices overlap on small phones', seo: 'Titles and descriptions for search engines',
      golive: 'Go-live and DNS switch', training: 'Short training for the café team', call: 'Weekly status call with the client',
      gift: 'Birthday present for Anna', dentist: 'Book a dentist appointment', plants: 'Water the plants', book: 'Finish the book for the reading club',
      grandma: 'Call grandma', groceries: 'Buy oat milk and coffee beans', idea: 'Idea: try the new bakery around the corner',
      time1: 'Workshop and minutes', time2: 'Layouts, first round', time3: 'Staging setup',
    },
    tags: {client: 'client', web: 'web', home: 'home'},
  },
  de: {
    banner: 'Demo – deine Daten bleiben in diesem Browser', reset: 'Demo zurücksetzen', install: 'Kalmido installieren',
    resetAsk: 'Demo zurücksetzen? Alles, was du hier geändert hast, wird gelöscht und die Beispieldaten kommen zurück.',
    gated: 'In der Demo nicht verfügbar – installiere Kalmido (5 Minuten)', gatedMore: 'Dafür braucht es einen Server: Push-Benachrichtigungen, Kalender-Sync, Agenten, Git, Webhooks, Anmeldung über Anbieter und die Zusammenarbeit mit anderen laufen auf deinem eigenen Kalmido.',
    installLink: 'In 5 Minuten installieren', close: 'Schließen', simulated: 'simuliert',
    agentName: 'Demo-Agent', agentTexts: ['simuliert: prüft das Kontaktformular', 'simuliert: schreibt den Testbericht', 'simuliert: wartet auf deine Freigabe'],
    agentDone: 'simuliert: Testseite veröffentlicht', agentChatHello: 'Hallo! Ich bin ein simulierter Agent. In einem echten Kalmido arbeitet ein KI-Assistent oder ein Bot über die API in geteilten Listen mit, und du gibst frei, was wichtig ist.',
    agentChatOk: 'Danke – (simuliert) die Testseite ist online. Den Testbericht schreibe ich als Kommentar.', agentChatNo: 'Verstanden – (simuliert) ich veröffentliche nichts und warte auf deine Rückmeldung.',
    agentChatReply: 'Das ist die Demo: Ich antworte nur mit vorbereiteten Sätzen. Installiere Kalmido, um einen echten Agenten anzubinden.',
    jobTitle: 'Testseite für die Abnahme durch den Kunden veröffentlichen?', jobLog: 'Build und Links geprüft. Warte auf deine Freigabe.',
    project: 'Website-Relaunch für Café Aurora', secs: ['Analyse', 'Design', 'Entwicklung', 'Launch'],
    personal: 'Privat', budget: 'Budget', effort: 'Aufwand', small: 'Klein', medium: 'Mittel', large: 'Groß',
    status: 'Design ist abgenommen, die Entwicklung liegt im Plan', ms1: 'Design abgenommen', ms2: 'Go-live',
    t: {
      kickoff: 'Kickoff-Workshop mit dem Kunden', sitemap: 'Sitemap und Inhaltsplan entwerfen', moodboard: 'Moodboard und Farbpalette',
      layouts: 'Layouts für Startseite und Speisekarte', layoutsNote: '**Ziel:** eine warme, ruhige Seite, die das Frühstücksangebot verkauft.\n\n- [x] Zuerst fürs Handy\n- [ ] Desktop-Variante\n- [ ] Barrierefreiheit prüfen (Kontrast, Schriftgröße)',
      subA: 'Startseite', subB: 'Speisekarte', subC: 'Kontakt und Öffnungszeiten',
      approval: 'Design vom Kunden abnehmen lassen', comment: 'Der Kundin gefallen die warmen Farben, sie wünscht größere Fotos von den Kuchen.',
      cms: 'CMS und Testseite einrichten', form: 'Kontaktformular verschickt keine Bestätigungsmail', booking: 'Tischreservierung auf der Startseite',
      images: 'Fotos optimieren (WebP, Lazy Loading)', menuBug: 'Preise der Speisekarte überlappen auf kleinen Handys', seo: 'Titel und Beschreibungen für Suchmaschinen',
      golive: 'Go-live und DNS-Umstellung', training: 'Kurze Schulung für das Café-Team', call: 'Wöchentlicher Status-Call mit dem Kunden',
      gift: 'Geburtstagsgeschenk für Anna', dentist: 'Zahnarzttermin vereinbaren', plants: 'Pflanzen gießen', book: 'Buch für den Lesekreis fertig lesen',
      grandma: 'Oma anrufen', groceries: 'Hafermilch und Kaffeebohnen kaufen', idea: 'Idee: die neue Bäckerei um die Ecke ausprobieren',
      time1: 'Workshop und Protokoll', time2: 'Layouts, erste Runde', time3: 'Testseite aufsetzen',
    },
    tags: {client: 'kunde', web: 'web', home: 'zuhause'},
  },
  fr: {
    banner: 'Démo – vos données restent dans ce navigateur', reset: 'Réinitialiser la démo', install: 'Installer Kalmido',
    resetAsk: 'Réinitialiser la démo ? Tout ce que vous avez modifié ici est supprimé et les données d’exemple reviennent.',
    gated: 'Indisponible dans la démo – installez Kalmido (5 minutes)', gatedMore: 'Il faut un serveur : notifications push, synchronisation de calendrier, agents, Git, webhooks, connexion via un fournisseur et travail à plusieurs fonctionnent sur votre propre Kalmido.',
    installLink: 'Installer en 5 minutes', close: 'Fermer', simulated: 'simulé',
    agentName: 'Demo-Agent', agentTexts: ['simulé : vérifie le formulaire de contact', 'simulé : rédige le rapport de test', 'simulé : attend votre validation'],
    agentDone: 'simulé : site de test publié', agentChatHello: 'Bonjour ! Je suis un agent simulé. Dans un vrai Kalmido, un assistant IA ou un bot travaille sur des listes partagées via l’API, et vous validez ce qui compte.',
    agentChatOk: 'Merci – (simulé) le site de test est en ligne. Je publierai le rapport de test en commentaire.', agentChatNo: 'Compris – (simulé) je ne publie rien et j’attends votre retour.',
    agentChatReply: 'Ceci est la démo : je ne réponds qu’avec des phrases préparées. Installez Kalmido pour connecter un vrai agent.',
    jobTitle: 'Publier le site de test pour la validation du client ?', jobLog: 'Build et liens vérifiés. En attente de votre validation.',
    project: 'Refonte du site du Café Aurora', secs: ['Analyse', 'Design', 'Développement', 'Lancement'],
    personal: 'Personnel', budget: 'Budget', effort: 'Effort', small: 'Petit', medium: 'Moyen', large: 'Grand',
    status: 'Le design est validé, le développement est dans les temps', ms1: 'Design validé', ms2: 'Mise en ligne',
    t: {
      kickoff: 'Atelier de lancement avec le client', sitemap: 'Ébaucher l’arborescence et le plan de contenu', moodboard: 'Planche d’ambiance et palette de couleurs',
      layouts: 'Maquettes de l’accueil et de la carte', layoutsNote: '**Objectif :** un site chaleureux et calme qui met en valeur les petits-déjeuners.\n\n- [x] Mobile d’abord\n- [ ] Version ordinateur\n- [ ] Vérifier l’accessibilité (contraste, taille du texte)',
      subA: 'Page d’accueil', subB: 'Page de la carte', subC: 'Contact et horaires',
      approval: 'Faire valider le design par le client', comment: 'La cliente aime les couleurs chaudes et souhaite des photos de gâteaux plus grandes.',
      cms: 'Installer le CMS et le site de test', form: 'Le formulaire de contact n’envoie pas d’e-mail de confirmation', booking: 'Réservation de table sur l’accueil',
      images: 'Optimiser les photos (WebP, chargement différé)', menuBug: 'Les prix de la carte se chevauchent sur les petits téléphones', seo: 'Titres et descriptions pour les moteurs de recherche',
      golive: 'Mise en ligne et bascule DNS', training: 'Courte formation pour l’équipe du café', call: 'Point hebdomadaire avec le client',
      gift: 'Cadeau d’anniversaire pour Anna', dentist: 'Prendre rendez-vous chez le dentiste', plants: 'Arroser les plantes', book: 'Finir le livre pour le club de lecture',
      grandma: 'Appeler mamie', groceries: 'Acheter du lait d’avoine et du café en grains', idea: 'Idée : essayer la nouvelle boulangerie du coin',
      time1: 'Atelier et compte rendu', time2: 'Maquettes, premier tour', time3: 'Mise en place du site de test',
    },
    tags: {client: 'client', web: 'web', home: 'maison'},
  },
  es: {
    banner: 'Demo – tus datos se quedan en este navegador', reset: 'Restablecer la demo', install: 'Instalar Kalmido',
    resetAsk: '¿Restablecer la demo? Se borra todo lo que cambiaste aquí y vuelven los datos de ejemplo.',
    gated: 'No disponible en la demo – instala Kalmido (5 minutos)', gatedMore: 'Esto necesita un servidor: notificaciones push, sincronización de calendarios, agentes, Git, webhooks, inicio de sesión con proveedores y el trabajo con otras personas funcionan en tu propio Kalmido.',
    installLink: 'Instalar en 5 minutos', close: 'Cerrar', simulated: 'simulado',
    agentName: 'Demo-Agent', agentTexts: ['simulado: revisa el formulario de contacto', 'simulado: escribe el informe de pruebas', 'simulado: espera tu aprobación'],
    agentDone: 'simulado: sitio de pruebas publicado', agentChatHello: '¡Hola! Soy un agente simulado. En un Kalmido real, un asistente de IA o un bot trabaja en listas compartidas a través de la API, y tú apruebas lo importante.',
    agentChatOk: 'Gracias – (simulado) el sitio de pruebas está en línea. Publicaré el informe de pruebas como comentario.', agentChatNo: 'Entendido – (simulado) no publico nada y espero tus comentarios.',
    agentChatReply: 'Esto es la demo: solo respondo con frases preparadas. Instala Kalmido para conectar un agente real.',
    jobTitle: '¿Publicar el sitio de pruebas para la revisión del cliente?', jobLog: 'Build y enlaces revisados. Esperando tu aprobación.',
    project: 'Nueva web para el Café Aurora', secs: ['Análisis', 'Diseño', 'Desarrollo', 'Lanzamiento'],
    personal: 'Personal', budget: 'Presupuesto', effort: 'Esfuerzo', small: 'Pequeño', medium: 'Medio', large: 'Grande',
    status: 'El diseño está aprobado, el desarrollo va según lo previsto', ms1: 'Diseño aprobado', ms2: 'Puesta en marcha',
    t: {
      kickoff: 'Taller inicial con el cliente', sitemap: 'Esbozar el mapa del sitio y el plan de contenidos', moodboard: 'Moodboard y paleta de colores',
      layouts: 'Maquetas de la portada y la carta', layoutsNote: '**Objetivo:** una web cálida y tranquila que venda los desayunos.\n\n- [x] Primero el móvil\n- [ ] Versión de escritorio\n- [ ] Revisar la accesibilidad (contraste, tamaño de letra)',
      subA: 'Portada', subB: 'Página de la carta', subC: 'Contacto y horario',
      approval: 'Conseguir la aprobación del diseño', comment: 'A la clienta le gustan los colores cálidos y quiere fotos más grandes de las tartas.',
      cms: 'Configurar el CMS y el sitio de pruebas', form: 'El formulario de contacto no envía el correo de confirmación', booking: 'Reserva de mesa en la portada',
      images: 'Optimizar las fotos (WebP, carga diferida)', menuBug: 'Los precios de la carta se solapan en móviles pequeños', seo: 'Títulos y descripciones para buscadores',
      golive: 'Puesta en marcha y cambio de DNS', training: 'Formación breve para el equipo del café', call: 'Llamada semanal de seguimiento con el cliente',
      gift: 'Regalo de cumpleaños para Anna', dentist: 'Pedir cita con el dentista', plants: 'Regar las plantas', book: 'Terminar el libro del club de lectura',
      grandma: 'Llamar a la abuela', groceries: 'Comprar bebida de avena y café en grano', idea: 'Idea: probar la nueva panadería de la esquina',
      time1: 'Taller y acta', time2: 'Maquetas, primera ronda', time3: 'Montar el sitio de pruebas',
    },
    tags: {client: 'cliente', web: 'web', home: 'casa'},
  },
  it: {
    banner: 'Demo – i tuoi dati restano in questo browser', reset: 'Reimposta la demo', install: 'Installa Kalmido',
    resetAsk: 'Reimpostare la demo? Tutto ciò che hai cambiato qui viene eliminato e tornano i dati di esempio.',
    gated: 'Non disponibile nella demo – installa Kalmido (5 minuti)', gatedMore: 'Serve un server: notifiche push, sincronizzazione del calendario, agenti, Git, webhook, accesso tramite provider e il lavoro con altre persone funzionano sul tuo Kalmido.',
    installLink: 'Installa in 5 minuti', close: 'Chiudi', simulated: 'simulato',
    agentName: 'Demo-Agent', agentTexts: ['simulato: controlla il modulo di contatto', 'simulato: scrive il rapporto di test', 'simulato: attende la tua approvazione'],
    agentDone: 'simulato: sito di prova pubblicato', agentChatHello: 'Ciao! Sono un agente simulato. In un vero Kalmido un assistente IA o un bot lavora sulle liste condivise tramite l’API, e tu approvi ciò che conta.',
    agentChatOk: 'Grazie – (simulato) il sito di prova è online. Pubblicherò il rapporto di test come commento.', agentChatNo: 'Capito – (simulato) non pubblico nulla e aspetto il tuo riscontro.',
    agentChatReply: 'Questa è la demo: rispondo solo con frasi preparate. Installa Kalmido per collegare un agente vero.',
    jobTitle: 'Pubblicare il sito di prova per la revisione del cliente?', jobLog: 'Build e link controllati. In attesa della tua approvazione.',
    project: 'Nuovo sito per il Café Aurora', secs: ['Analisi', 'Design', 'Sviluppo', 'Lancio'],
    personal: 'Personale', budget: 'Budget', effort: 'Impegno', small: 'Piccolo', medium: 'Medio', large: 'Grande',
    status: 'Il design è approvato, lo sviluppo è nei tempi', ms1: 'Design approvato', ms2: 'Messa online',
    t: {
      kickoff: 'Workshop iniziale con il cliente', sitemap: 'Bozza della mappa del sito e del piano dei contenuti', moodboard: 'Moodboard e palette di colori',
      layouts: 'Layout della home e del menu', layoutsNote: '**Obiettivo:** un sito caldo e tranquillo che valorizzi le colazioni.\n\n- [x] Prima il telefono\n- [ ] Versione desktop\n- [ ] Verificare l’accessibilità (contrasto, dimensione del testo)',
      subA: 'Home page', subB: 'Pagina del menu', subC: 'Contatti e orari',
      approval: 'Far approvare il design dal cliente', comment: 'Alla cliente piacciono i colori caldi e vuole foto più grandi delle torte.',
      cms: 'Configurare il CMS e il sito di prova', form: 'Il modulo di contatto non invia l’e-mail di conferma', booking: 'Prenotazione del tavolo nella home',
      images: 'Ottimizzare le foto (WebP, caricamento differito)', menuBug: 'I prezzi del menu si sovrappongono sui telefoni piccoli', seo: 'Titoli e descrizioni per i motori di ricerca',
      golive: 'Messa online e cambio DNS', training: 'Breve formazione per lo staff del café', call: 'Chiamata settimanale con il cliente',
      gift: 'Regalo di compleanno per Anna', dentist: 'Prenotare il dentista', plants: 'Innaffiare le piante', book: 'Finire il libro per il club di lettura',
      grandma: 'Chiamare la nonna', groceries: 'Comprare latte d’avena e caffè in grani', idea: 'Idea: provare il nuovo forno dietro l’angolo',
      time1: 'Workshop e verbale', time2: 'Layout, primo giro', time3: 'Allestire il sito di prova',
    },
    tags: {client: 'cliente', web: 'web', home: 'casa'},
  },
  nl: {
    banner: 'Demo – je gegevens blijven in deze browser', reset: 'Demo resetten', install: 'Kalmido installeren',
    resetAsk: 'Demo resetten? Alles wat je hier hebt veranderd wordt verwijderd en de voorbeeldgegevens komen terug.',
    gated: 'Niet beschikbaar in de demo – installeer Kalmido (5 minuten)', gatedMore: 'Hiervoor is een server nodig: pushmeldingen, agendasynchronisatie, agents, Git, webhooks, inloggen via een provider en samenwerken met anderen draaien op je eigen Kalmido.',
    installLink: 'In 5 minuten installeren', close: 'Sluiten', simulated: 'gesimuleerd',
    agentName: 'Demo-Agent', agentTexts: ['gesimuleerd: controleert het contactformulier', 'gesimuleerd: schrijft het testrapport', 'gesimuleerd: wacht op je goedkeuring'],
    agentDone: 'gesimuleerd: testsite gepubliceerd', agentChatHello: 'Hoi! Ik ben een gesimuleerde agent. In een echte Kalmido werkt een AI-assistent of bot via de API mee in gedeelde lijsten, en jij keurt goed wat ertoe doet.',
    agentChatOk: 'Bedankt – (gesimuleerd) de testsite staat online. Het testrapport zet ik als reactie erbij.', agentChatNo: 'Begrepen – (gesimuleerd) ik publiceer niets en wacht op je feedback.',
    agentChatReply: 'Dit is de demo: ik antwoord alleen met voorbereide zinnen. Installeer Kalmido om een echte agent te koppelen.',
    jobTitle: 'De testsite publiceren voor de review door de klant?', jobLog: 'Build en links gecontroleerd. Wacht op je goedkeuring.',
    project: 'Nieuwe website voor Café Aurora', secs: ['Analyse', 'Ontwerp', 'Ontwikkeling', 'Lancering'],
    personal: 'Privé', budget: 'Budget', effort: 'Inspanning', small: 'Klein', medium: 'Middel', large: 'Groot',
    status: 'Het ontwerp is goedgekeurd, de ontwikkeling ligt op schema', ms1: 'Ontwerp goedgekeurd', ms2: 'Livegang',
    t: {
      kickoff: 'Kick-offworkshop met de klant', sitemap: 'Sitemap en contentplan opzetten', moodboard: 'Moodboard en kleurenpalet',
      layouts: 'Layouts voor de homepage en de menukaart', layoutsNote: '**Doel:** een warme, rustige site die het ontbijt verkoopt.\n\n- [x] Eerst mobiel\n- [ ] Desktopversie\n- [ ] Toegankelijkheid controleren (contrast, lettergrootte)',
      subA: 'Homepage', subB: 'Menukaart', subC: 'Contact en openingstijden',
      approval: 'Ontwerp laten goedkeuren door de klant', comment: 'De klant vindt de warme kleuren mooi en wil grotere foto’s van de taarten.',
      cms: 'CMS en testsite inrichten', form: 'Contactformulier stuurt geen bevestigingsmail', booking: 'Tafel reserveren op de homepage',
      images: 'Foto’s optimaliseren (WebP, lazy loading)', menuBug: 'Prijzen op de menukaart overlappen op kleine telefoons', seo: 'Titels en beschrijvingen voor zoekmachines',
      golive: 'Livegang en DNS-omzetting', training: 'Korte training voor het caféteam', call: 'Wekelijks statusgesprek met de klant',
      gift: 'Verjaardagscadeau voor Anna', dentist: 'Afspraak bij de tandarts maken', plants: 'Planten water geven', book: 'Het boek voor de leesclub uitlezen',
      grandma: 'Oma bellen', groceries: 'Havermelk en koffiebonen kopen', idea: 'Idee: de nieuwe bakker om de hoek proberen',
      time1: 'Workshop en verslag', time2: 'Layouts, eerste ronde', time3: 'Testsite opzetten',
    },
    tags: {client: 'klant', web: 'web', home: 'thuis'},
  },
};
